title: Didier Allexandre
logo: /images/Didier Allexandre2.jpg #/assets/img/logo.png
description: Minimal is a theme for GitHub Pages.
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
[LinkedIn Profile](https://www.linkedin.com/in/didier-allexandre-269b9b12/)
[ResearchGate Profile](https://www.researchgate.net/profile/Didier-Allexandre)
[Scholar Profile](https://scholar.google.com/citations?hl=en&user=lHPH2fgAAAAJ)
