title: Didier Allexandre
logo: /images/Didier Allexandre2.jpg #/assets/img/logo.png
description: Minimal is a theme for GitHub Pages.
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
